Update nut-notify

diff --git a/source/nut-dw/usr/sbin/nut-notify b/source/nut-dw/usr/sbin/nut-notify
--- a/source/nut-dw/usr/sbin/nut-notify
+++ b/source/nut-dw/usr/sbin/nut-notify
@@ -56,7 +56,11 @@ then
             ( ONLINE 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
         fi
         echo "[${NAME}] UPS is online, any planned shutdowns were cancelled." | tee >(wall) >(logger -t "nut-notify")
-        $NOTIFY -e "${EVENT}" -s "Notice ${SUBJECT} Online" -d "UPS is online, any planned shutdowns were cancelled." -i "normal"
+
+        timeout -s9 10 $NOTIFY -e "${EVENT}" -s "Notice ${SUBJECT} Online" -d "UPS is online, any planned shutdowns were cancelled." -i "normal"
+        if [ $? -gt 100 ]; then
+            echo "OS notification could not be sent within 10 seconds..." | logger -t "nut-notify"
+        fi
 
         # Cause all instances of this script to exit.
         killall -s SIGTERM "$(basename "$0")"
@@ -67,7 +71,11 @@ then
             ( ONBATT 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
         fi
         echo "[${NAME}] UPS is on battery. ${MESSAGE}" | tee >(wall) >(logger -t "nut-notify")
-        $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} On Battery" -d "UPS is on battery. ${MESSAGE}" -i "alert"
+
+        timeout -s9 10 $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} On Battery" -d "UPS is on battery. ${MESSAGE}" -i "alert"
+        if [ $? -gt 100 ]; then
+            echo "OS notification could not be sent within 10 seconds..." | logger -t "nut-notify"
+        fi
 
         if [ "$SHUTDOWN" != "none" ]; then
             if [ "$SHUTDOWN" == "sec_timer" ]; then
@@ -93,7 +101,12 @@ then
                 ( ONBATT_SHUTDOWN 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
             fi
             echo "[${NAME}] UNRAID is being gracefully shutdown from a UPS power event." | tee >(wall) >(logger -t "nut-notify")
-            $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} Shutdown" -d "UNRAID is being gracefully shutdown from a UPS power event." -i "alert"
+
+            timeout -s9 10 $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} Shutdown" -d "UNRAID is being gracefully shutdown from a UPS power event." -i "alert"
+            if [ $? -gt 100 ]; then
+                echo "OS notification could not be sent within 10 seconds..." | logger -t "nut-notify"
+            fi
+
             /usr/sbin/upsmon -c fsd
         fi
 
@@ -104,14 +117,22 @@ then
                 ( REPLBATT 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
             fi
             echo "[${NAME}] UPS reports that its batteries need replacement." | tee >(wall) >(logger -t "nut-notify")
-            $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} Battery Replacement" -d "UPS reports that its batteries need replacement." -i "alert"
+
+            timeout -s9 10 $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT} Battery Replacement" -d "UPS reports that its batteries need replacement." -i "alert"
+            if [ $? -gt 100 ]; then
+                echo "OS notification could not be sent within 10 seconds..." | logger -t "nut-notify"
+            fi
         fi
 
 # for any other status messages the user has configured to be reported
 else
         if [ "$(type -t "$NOTIFYTYPE")" == "function" ]; then
-            ( eval "$NOTIFYTYPE" 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
+            ( "$NOTIFYTYPE" 2>&1 | logger -t "xnut-notify-hooks.sh" ) &
         fi
         echo "[${NAME}] ${1}" | tee >(wall) >(logger -t "nut-notify")
-        $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT}" -d "$1" -i "alert"
+
+        timeout -s9 10 $NOTIFY -e "${EVENT}" -s "Alert ${SUBJECT}" -d "$1" -i "alert"
+        if [ $? -gt 100 ]; then
+            echo "OS notification could not be sent within 10 seconds..." | logger -t "nut-notify"
+        fi
 fi
